#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 720
#define MAP_COORDS_X 10.0f
#define MAP_COORDS_Y ((MAP_COORDS_X)*((f32)WINDOW_HEIGHT/(f32)WINDOW_WIDTH))
#define METERS_TO_PIXEL ((WINDOW_WIDTH * 0.5f) / MAP_COORDS_X)

