#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600
#define MAP_COORDS_X 10.0f
#define MAP_COORDS_Y ((MAP_COORDS_X)*((f32)WINDOW_HEIGHT/(f32)WINDOW_WIDTH))
#define METERS_TO_PIXEL ((WINDOW_WIDTH * 0.5f) / (MAP_COORDS_X*0.5f))
#define PIXEL_TO_METERS (1.0f/(f32)METERS_TO_PIXEL)

