#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600
#define BACK_BUFFER_WIDTH 1920
#define BACK_BUFFER_HEIGHT 1080
#define MAP_COORDS_X 10.0f
#define MAP_COORDS_Y ((MAP_COORDS_X)*((f32)BACK_BUFFER_HEIGHT/(f32)BACK_BUFFER_WIDTH))
#define METERS_TO_PIXEL ((BACK_BUFFER_WIDTH * 0.5f) / (MAP_COORDS_X*0.5f))
#define PIXEL_TO_METERS (1.0f/(f32)METERS_TO_PIXEL)
#define MAX_PATH 1048

